git-svn-id: http://192.168.20.11/sequoiadb/trunk@10346 6121f079-4a18-41d3-8c30-8870a322f2c2

diff --git a/script/sdbperfcol b/script/sdbperfcol
--- a/script/sdbperfcol
+++ b/script/sdbperfcol
@@ -29,24 +29,28 @@ INSTALLDIR=`/bin/pwd`
 cd ${INSTALLDIR?}
 INSTALLDIR=`dirname ${INSTALLDIR?}`
 LOCALCONFIGDIR="${INSTALLDIR?}/conf/local"
+BINDIR="${INSTALLDIR?}/bin"
 cd ${CURDIR?}
 
 # function to print usage
 function printUsage
 {
-   echo "Usage: sdbperfcol [-u <username> -p <password>] -s <port1>,<port2> ..."
+   echo "Usage: sdbperfcol [-h] [-u <username> -p <password>] [-l 0|1|2] -s <port1>,<port2> ..."
+   echo "-u         user name"
+   echo "-p         password"
+   echo "-l         service level, 0 for lowest, 2 for highest. Default: 0"
+   echo "-s         list of database service names, separated by comma"
+   echo "-h         show this help"
    exit
 }
 
 USERNAME=""
 PASSWORD=""
 SERVICENAME=""
-#set -a DATABASELIST
-#set -i DBNUM
-DBNUM=0
+SERVICELEVEL="0"
 
 # parse arguments
-while getopts ":u:p:s:h" option;
+while getopts ":u:p:s:l:h" option;
 do
    case $option in
       u)
@@ -61,6 +65,10 @@ do
          # collect local service name
          SERVICENAME=$OPTARG
          ;;
+      l)
+         # service level, 0 for lowest, 2 for highest
+         SERVICELEVEL=$OPTARG
+         ;;
       h)
          printUsage
          exit
@@ -71,6 +79,16 @@ do
          ;;  
    esac
 done
+
+# sanity check for service level
+if [ ${SERVICELEVEL?} != "0" ] && [ ${SERVICELEVEL?} != "1" ] && [ ${SERVICELEVEL?} != "2" ] ;
+then
+   echo "Invalid service level: ${SERVICELEVEL?}"
+   printUsage
+   exit
+fi
+
+NUMSERVICELEVEL=$((SERVICELEVEL))
 
 # convert service name into list
 DBLISTSIZE=0
@@ -120,9 +138,9 @@ mkdir OSCONFIG >> sdbperfcol.log 2>&1
 # dir for sequoiadb configurations
 mkdir SDBCONFIG >> sdbperfcol.log 2>&1
 # dir for operating system performance data
-mkdir OSSNAP >> sdbperfcol.log 2>&1
+mkdir OSSNAPS >> sdbperfcol.log 2>&1
 # dir for sequoiadb performance data
-mkdir SDBSNAP >> sdbperfcol.log 2>&1
+mkdir SDBSNAPS >> sdbperfcol.log 2>&1
 # dir for operating system trace
 mkdir OSTRACE >> sdbperfcol.log 2>&1
 # dir for sequoiadb trace
@@ -133,26 +151,26 @@ mkdir SDBTRACE >> sdbperfcol.log 2>&1
 # the file should be remain in the current directory
 function tarfiles
 {
-# tar the files
-tar -cvf sdbperfcol.out.tar OSCONFIG SDBCONFIG OSSNAP SDBSNAP \
-         OSTRACE SDBTRACE sdbperfcol.* 2>&1
-# if the tar success, let's remove the directories
-if [ $? -eq 0 ] ; then
-   echo "removing directories... "
-   rm -Rf OSCONFIG SDBCONFIG OSSNAP SDBSNAP OSTRACE SDBTRACE
-fi
-# get the current timestamp
-datestamp=`date +"%m%d"`.`date +"%H%M"`
-# rename the file with current timestamp
-mv sdbperfcol.out.tar sdbperfcol.$datestamp.tar
-# zip the file
-gzip sdbperfcol.$datestamp.tar
-# echo informational messages
-echo "output files have been tarred and compressed into sdbperfcol.$datestamp.tar.gz" `date` | tee -a sdbperfcol.log
-echo ""
-echo "This file should be sent to SequoiaDB support for further analyze"
-echo "Thank you"
-echo ""
+   # tar the files
+   tar -cvf sdbperfcol.out.tar OSCONFIG SDBCONFIG OSSNAPS SDBSNAPS \
+            OSTRACE SDBTRACE sdbperfcol.* 2>&1
+   # if the tar success, let's remove the directories
+   if [ $? -eq 0 ] ; then
+      echo "removing directories... "
+      rm -Rf OSCONFIG SDBCONFIG OSSNAPS SDBSNAPS OSTRACE SDBTRACE
+   fi
+   # get the current timestamp
+   datestamp=`date +"%m%d"`.`date +"%H%M"`
+   # rename the file with current timestamp
+   mv sdbperfcol.out.tar sdbperfcol.$datestamp.tar
+   # zip the file
+   gzip sdbperfcol.$datestamp.tar
+   # echo informational messages
+   echo "output files have been tarred and compressed into sdbperfcol.$datestamp.tar.gz" `date` | tee -a sdbperfcol.log
+   echo ""
+   echo "This file should be sent to SequoiaDB support for further analyze"
+   echo "Thank you"
+   echo ""
 }
 
 # if ctrl-c happened during the execution, it will trigger the script to
@@ -169,6 +187,7 @@ echo ""
 echo ""
 sleep 5
 
+
 #OS CONFIG INFO
 echo "started OS CONFIG info" `date` | tee -a sdbperfcol.log
 echo "should complete in less than one minute"
@@ -177,6 +196,8 @@ ipcs -l >> OSCONFIG/machine.cfg 2>&1
 ls -l /dev >> OSCONFIG/machine.cfg 2>&1
 rpm -qa > OSCONFIG/rpm_qa.txt 2>&1
 dmesg > OSCONFIG/dmesg.txt 2>&1
+mkdir -p OSCONFIG/proc/sys/vm 2>&1
+cp /proc/sys/vm/* OSCONFIG/proc/sys/vm 2>/dev/null
 echo "finished OS CONFIG info" `date` | tee -a sdbperfcol.log
 echo "" | tee -a sdbperfcol.log
 
@@ -192,5 +213,168 @@ do
    # verify the existance of file
    cp ${FILENAME?} SDBCONFIG/sdb.conf.$x 2>&1
 done
+# get SequoiaDB database version
+${INSTALLDIR?}/bin/sequoiadb --version > SDBCONFIG/sdb.version 2>&1
+echo "finished basic SequoiaDB CONFIG info" `date` | tee -a sdbperfcol.log
+echo "" | tee -a sdbperfcol.log
+
+#OS MONITOR info 1
+echo "start first iteration of OS monitor info" `date` | tee -a sdbperfcol.log
+echo "should complete in less than 2 minutes"
+uptime > OSSNAPS/netstat.1 2>&1
+netstat -v >> OSSNAPS/netstat.1 2>&1
+uptime > OSSNAPS/nfsstat.1 2>&1
+nfsstat >> OSSNAPS/nfsstat.1 2>&1
+uptime > OSSNAPS/vmstat.1 2>&1
+vmstat 1 10 >> OSSNAPS/vmstat.1 2>&1
+uptime > OSSNAPS/swapon.1 2>&1
+swapon -s >> OSSNAPS/swapon.1 2>&1
+uptime > OSSNAPS/free.1 2>&1
+free >> OSSNAPS/free.1 2>&1
+uptime > OSSNAPS/pself.1 2>&1
+ps -elf | sort +5 -rn >> OSSNAPS/pself.1 2>&1
+top -b -n 1 > OSSNAPS/top.b 2>&1
+uptime > OSSNAPS/ipcs.1 2>&1
+ipcs -a >> OSSNAPS/ipcs.1 2>&1
+echo "finished first iteration of OS monitor info" `date` | tee -a sdbperfcol.log
+echo "" | tee -a sdbperfcol.log
+sleep 30
+
+#OS MONITOR info 2
+echo "start second iteration of OS monitor info" `date` | tee -a sdbperfcol.log
+echo "should complete in less than 2 minutes"
+uptime > OSSNAPS/netstat.2 2>&1
+netstat -v >> OSSNAPS/netstat.2 2>&1
+uptime > OSSNAPS/nfsstat.2 2>&1
+nfsstat >> OSSNAPS/nfsstat.2 2>&1
+uptime > OSSNAPS/vmstat.2 2>&1
+vmstat 1 10 >> OSSNAPS/vmstat.2 2>&1
+uptime > OSSNAPS/swapon.2 2>&1
+swapon -s >> OSSNAPS/swapon.2 2>&1
+uptime > OSSNAPS/free.2 2>&1
+free >> OSSNAPS/free.2 2>&1
+uptime > OSSNAPS/pself.2 2>&1
+ps -elf | sort +5 -rn >> OSSNAPS/pself.2 2>&1
+top -b -n 1 > OSSNAPS/top.b 2>&1
+uptime > OSSNAPS/ipcs.2 2>&1
+ipcs -a >> OSSNAPS/ipcs.2 2>&1
+echo "finished second iteration of OS monitor info" `date` | tee -a sdbperfcol.log
+echo "" | tee -a sdbperfcol.log
+
+#DB Monitor info
+echo "start SequoiaDB monitor info" `date` | tee -a sdbperfcol.log
+echo "should complete in less than 2 minutes for each database service"
+# loop for each database
+for x in $DATABASELIST
+do
+   # create snapshot file
+   uptime > SDBSNAPS/snapshot.$x 2>&1
+   # connect to database
+   ${BINDIR?}/sdb "var db=new Sdb('localhost', $x, '${USERNAME?}', '${PASSWORD?}')"
+   # make sure connection is established
+   if [ $? -ne 0 ] ;
+   then
+      echo "Unable to connect to service $x" >> SDBSNAPS/snapshot.$x 2>&1
+   else
+      # each database collect 5 snapshots
+      for i in 1 2 3 4 5
+      do
+         echo "[$i]Context Snapshot: " `date` >> SDBSNAPS/snapshot_context.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_CONTEXTS)" >> SDBSNAPS/snapshot_context.$x 2>&1
+         echo "[$i]Session Snapshot: " `date` >> SDBSNAPS/snapshot_session.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_SESSIONS)" >> SDBSNAPS/snapshot_session.$x 2>&1
+         echo "[$i]Database Snapshot: " `date` >> SDBSNAPS/snapshot_database.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_DATABASE)" >> SDBSNAPS/snapshot_database.$x 2>&1
+         echo "[$i]System Snapshot: " `date` >> SDBSNAPS/snapshot_system.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_SYSTEM)" >> SDBSNAPS/snapshot_system.$x 2>&1
+         echo "[$i]Collection Snapshot:" `date` >> SDBSNAPS/snapshot_collection.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_COLLECTIONS)" >> SDBSNAPS/snapshot_collection.$x 2>&1
+         echo "[$i]CollectionSpace Snapshot:" `date` >> SDBSNAPS/snapshot_collectionspace.$x 2>&1
+         ${BINDIR?}/sdb "db.snapshot(SDB_SNAP_COLLECTIONSPACES)" >> SDBSNAPS/snapshot_collectionspace.$x 2>&1
+         sleep 10
+      done
+      ${BINDIR?}/sdb "quit"
+   fi
+done
+echo "finished SequoiaDB monitor info" `date` | tee -a sdbperfcol.log
+echo "" | tee -a sdbperfcol.log
+
+# SERVICE LEVEL 1 or higher
+# STACK
+if [ $NUMSERVICELEVEL -gt 0 ] ;
+then
+   # STACK
+   echo "start SequoiaDB stack collection" `date` | tee -a sdbperfcol.log
+   echo "should complete in less than 3 minutes for each database service"
+   for x in $DATABASELIST
+   do
+      echo "Collecting first iteration of call stack for $x" | tee -a sdbperfcol.log
+      kill -23 `ps -elf | grep "sequoiadb($x)" | grep -v grep | awk '{print $4}'`
+      sleep 30
+      echo "Collecting second iteration of call stack for $x" | tee -a sdbperfcol.log
+      kill -23 `ps -elf | grep "sequoiadb($x)" | grep -v grep | awk '{print $4}'`
+      sleep 30
+      echo "Collecting third iteration of call stack for $x" | tee -a sdbperfcol.log
+      kill -23 `ps -elf | grep "sequoiadb($x)" | grep -v grep | awk '{print $4}'`
+      # wait for getconfig to be implemented in database engine, before collecting
+      # trap files from diaglog directory
+   done
+   echo "finished SequoiaDB stack collection" `date` | tee -a sdbperfcol.log
+   echo "" | tee -a sdbperfcol.log
+fi
+
+# SERVICE LEVEL 2 or higher
+# STRACE + Database Trace
+if [ $NUMSERVICELEVEL -gt 1 ] ;
+then
+   echo "start strace collection" `date` | tee -a sdbperfcol.log
+   echo "should complete in less than 2 minutes for each database service"
+   for x in $DATABASELIST
+   do
+      echo "Collecting starce for $x" | tee -a sdbperfcol.log
+      PID=`ps -elf | grep "sequoiadb($x)" | grep -v grep | awk '{print $4}'`
+      strace -f -tt -T -o OSTRACE/strace.$x.out -p $PID &
+      SPID=$!
+      sleep 60
+      kill -15 $SPID
+   done
+   echo "finished strace collection" `date` | tee -a sdbperfcol.log
+   echo "" | tee -a sdbperfcol.log
+
+   echo "start SequoiaDB trace collection" `date` | tee -a sdbperfcol.log
+   echo "should complete in less than 2 minutes for each database service"
+   for x in $DATABASELIST
+   do
+      echo "Collecting database trace for $x" | tee -a sdbperfcol.log
+      # connect to database
+      ${BINDIR?}/sdb "var db=new Sdb('localhost', $x, '${USERNAME?}', '${PASSWORD?}')"
+      # make sure connection is established
+      if [ $? -ne 0 ] ;
+      then
+         echo "Unable to connect to service $x" > SDBTRACE/trace.$x 2>&1
+      else
+         # each database collect trace for 60 seconds
+         ${BINDIR?}/sdb "db.traceOn(1000000000)" > SDBTRACE/trace.$x 2>&1
+         sleep 60
+         ${BINDIR?}/sdb "db.traceOff(\"${CURDIR?}/SDBTRACE/trc.$x.dmp\")" >> SDBTRACE/trace.$x 2>&1
+         ${BINDIR?}/sdb "quit"
+      fi
+   done
+   echo "finished SequoiaDB trace collection" `date` | tee -a sdbperfcol.log
+   echo "" | tee -a sdbperfcol.log
+
+   echo "start SequoiaDB trace format" `date` | tee -a sdbperfcol.log
+   for x in $DATABASELIST
+   do
+      if [ -f SDBTRACE/trc.$x.dmp ] ;
+      then
+         echo "Format database trace for $x" | tee -a sdbperfcol.log
+         ${BINDIR?}/sdb "traceFmt(SDB_TRACE_FLW,\"${CURDIR?}/SDBTRACE/trc.$x.dmp\",\"${CURDIR?}/SDBTRACE/trc.$x.flw\")" >> SDBTRACE/trace.$x 2>&1
+         ${BINDIR?}/sdb "traceFmt(SDB_TRACE_FMT,\"${CURDIR?}/SDBTRACE/trc.$x.dmp\",\"${CURDIR?}/SDBTRACE/trc.$x.fmt\")" >> SDBTRACE/trace.$x 2>&1
+      fi
+   done
+   echo "finished SequoiaDB trace format" `date` | tee -a sdbperfcol.log
+   echo "" | tee -a sdbperfcol.log
+fi
 
 tarfiles
